pipeline:
  build:
    image: golang:${GO_VERSION}
    environment:
      - GOOS=${GO_OS}
      - GOARCH=${GO_ARCH}
    commands:
      - go get golang.org/x/sys/windows/registry
      - go build -o ./release/WindowsVersion-$GOOS-$GOARCH-$GO_VERSION.exe
      - cp *.exe /release

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - release
    volumes:
      - /home/pminnebach/docker/release:/cache/pminnebach/dronetest

matrix:
  GO_VERSION:
    - 1.8
    - 1.7
    - latest
  GO_ARCH:
    - 386
    - amd64
  GO_OS:
    - windows
