pipeline:
  build:
    image: golang:${GO_VERSION}
    environment:
      - GOOS=${GO_OS}
      - GOARCH=${GO_ARCH}
    commands:
      - pwd
      - ls -al
      - go get golang.org/x/sys/windows/registry
      - pwd
      - ls -al
      - go build -o WindowsVersion_$GOOS_$GOARCH.exe
      - pwd
      - ls -al

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - node_modules
    volumes:
      - /home/pminnebach/docker/release:/cache

matrix:
  GO_VERSION:
    - 1.8
    - 1.7
    - latest
  GO_ARCH:
    - 386
    - amd64
  GO_OS:
    - windows
