pipeline:
  build:
    image: golang:${GO_VERSION}
    environment:
      - GOOS=${GO_OS}
      - GOARCH=${GO_ARCH}
    commands:
      - pwd
      - ls -al
      - go get -u golang.org/x/sys/windows/registry
      - gofmt -w $(find . -type f -name *.go | grep -v /vendor/)
      # Add if you have tests and use /vendor
#      - go test -cover $(go list ./... | grep -v /vendor/)
      # Add if you have tests and don't /vendor
#      - go test -cover $(go list ./...)
      - go build -o ./release/WindowsVersion-$GOOS-$GOARCH-$GO_VERSION.exe
      - pwd
      - ls -al
      - ls -al release/
      
  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - release
    volumes:
      - /home/pminnebach/docker/release:/cache/pminnebach/dronetest

matrix:
  GO_VERSION:
    - 1.8
    - 1.7
    - latest
  GO_ARCH:
    - 386
    - amd64
  GO_OS:
    - windows

